/**
 * Worker entrypoint.
 *
 * Wraps the OpenNext-generated worker so the Worker keeps a `scheduled`
 * handler alongside `fetch`. The generated `.open-next/worker.js` exports only
 * `fetch`, so deploying it directly would drop the scheduled handler that the
 * live Worker reports today and silently stop the three cleanup jobs.
 *
 * The cleanup jobs are ordinary API routes guarded by a `CRON_SECRET` bearer
 * token (they were Vercel HTTP crons originally). Rather than re-implement
 * them, each cron schedule is dispatched straight into the Next handler as a
 * synthetic request, so there is exactly one implementation of each job.
 *
 * `.open-next/worker.js` is generated by `npm run cf:build` and is gitignored;
 * it exists by the time wrangler bundles this file.
 */

import openNextWorker from '../.open-next/worker.js';

// Durable Object classes the OpenNext runtime declares. They must be re-exported
// from the entrypoint or the class bindings cannot resolve.
export { DOQueueHandler, DOShardedTagCache, BucketCachePurge } from '../.open-next/worker.js';

/** Cron expression -> the route that performs that job. Must match wrangler.jsonc. */
const CRON_ROUTES = {
  '0 3 * * *': '/api/auth/email/cleanup',
  '10 3 * * *': '/api/auth/password/cleanup',
  '20 3 * * *': '/api/security/rate-limit/cleanup',
};

const FALLBACK_ORIGIN = 'https://www.syllabus-sync.app';

export default {
  fetch(request, env, ctx) {
    return openNextWorker.fetch(request, env, ctx);
  },

  async scheduled(controller, env, ctx) {
    const path = CRON_ROUTES[controller.cron];
    if (!path) {
      console.warn(`[cron] no route mapped for schedule "${controller.cron}"`);
      return;
    }

    const origin = env.NEXT_PUBLIC_APP_URL || FALLBACK_ORIGIN;
    const request = new Request(new URL(path, origin), {
      method: 'GET',
      headers: {
        // The routes reject anything without this bearer token.
        authorization: `Bearer ${env.CRON_SECRET ?? ''}`,
        'user-agent': 'syllabus-sync-cron/1.0',
      },
    });

    const run = (async () => {
      try {
        const response = await openNextWorker.fetch(request, env, ctx);
        // Drain the body so the subrequest is allowed to complete.
        await response.arrayBuffer().catch(() => undefined);
        console.log(`[cron] ${controller.cron} -> ${path} ${response.status}`);
      } catch (error) {
        console.error(`[cron] ${controller.cron} -> ${path} failed:`, error);
      }
    })();

    // Keep the invocation alive until the job finishes.
    ctx.waitUntil(run);
    await run;
  },
};
